### ISSUE TITLE
Structure project

### ISSUE THREAD

**Issue by bestK1ngArthur** [BMSTUScheduleTeam/BMSTUSchedule#7]
Необходимо привести проект в порядок перед прикручиванием новых фич и собственного сервака.

**#TODO**
- [x] Убрать Firebase (Оставим только аналитику и пуши)
- [ ] <s>Восстановить работу пушей через Firebase</s>
- [x] Поправить структуру проекта (Разбить main.storyboard на кейсы)
- [x] Поправить визуальные баги на iOS 11 (Десятке вообще крышу сносит)
- [x] Поправить внутренную струткуру классов

**Comment by bestK1ngArthur** [comment]
Пуши откладываются до марта
